name: bds-project

services:
  spring-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${PROJECT_NAME}-server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
      - mongodb
    env_file:
      - ../.env
    networks:
      - bds-project-network
  postgres:
    image: postgres:13.11-bullseye
    container_name: ${PROJECT_NAME}-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    ports:
      - ${POSTGRESQL_EXTERNAL_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../var/logs/postgresql:/var/log/postgresql
    networks:
      - bds-project-network

  mongodb:
    image: mongo:7.0
    container_name: ${PROJECT_NAME}-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
    ports:
      - ${MONGODB_EXTERNAL_PORT}:27017
    volumes:
      - mongodb-data:/data/db
      - ../../var/logs/mongodb:/var/log/mongodb
    networks:
      - bds-project-network

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: template-mailhog
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - '1025:1025'
  #   networks:
  #     - template-network

volumes:
  postgres-data:
  mongodb-data:

networks:
  bds-project-network:
    driver: bridge
